MODEL:
  TYPE: 'pnet'
  SIZE: 12
  DEVICE: 'cpu'
  TRANSFORM: 'rcnn'
  BBOX_REG_WEIGHTS: (10., 10., 5., 5.)
  FOCAL_LOSS_ON: True
SOLVER:
  BASE_LR: 0.005
  GAMMA: 0.1
  STEPS: (10000, 30000, 50000)
  WARMUP_ITERS: 1000
TRAIN:
  BATCH_SIZE: 384
  LOSS_RATIO: (5.0, 1.0)
  MAX_ITERS: 70000
  DISPLAY: 50
FOCAL_LOSS:
  ALPHA: 0.25
  GAMMA: 2
