MODEL:
  TYPE: 'pnet'
  SIZE: 12
  TRANSFORM: 'rcnn'
  DEVICE: 'cuda'
  FOCAL_LOSS_ON: True
SOLVER:
  BASE_LR: 0.005
TRAIN:
  BATCH_SIZE: 384
  LOSS_RATIO: (5.0, 1.0)
FOCAL_LOSS:
  ALPHA: 0.25
  GAMMA: 2
TEST:
  PNET:
    THRESHOLD: 0.8
    NMS: (0.5, 0.5)
  RNET:
    THRESHOLD: 0.5
    NMS: 0.3
